### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [Mctavish38/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Summary:
Barry, congrats on finishing the Dasmoto project! You did an excellent job decomposing the spec sheet and structuring your HTML code by making use of classes and various elements appropriately. 

A couple of things I noticed were that you did not apply the bold blue color specified for all the prices. For a hint on how to implement this take a look at this [HTML](https://gist.github.com/jim-rosales/c1446e66054c97071406610be771fa79) and [CSS](https://gist.github.com/jim-rosales/2f5cfda50385ffddc1225f0e8a9f4807) solution for the project. This will not only help you see how to implement this feature but also see how the solution is commented. I reccomend you comment future files as they help increase the readability of your code which is crucial in a workplace environment when working in teams and need to promote collaboration amongst everyone.

**Comment by Mctavish38** [comment]
Thank you for the feedback! Totally new to all of this. I implemented the comments to make my code look easier to read. Still having trouble with the <h1> image showing up? Also the <h2> colors are not showing?

**Comment by jim-rosales** [comment]
Hey Barry! To help you with the image problem I'm guessing you mean the main one used for the banner? 

If it is try the following syntax:
```CSS
background: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
```

As for the colors not showing up, I'm guessing you're referring to the blue/bold for the prices can you show me the new CSS you're using? It seems you haven't pushed any changes to your repo so I can't see the changes you've made since your last commit.

**Comment by Mctavish38** [comment]
<!DOCTYPE html>
<html>
  <head>
    <title>Dasmoto's Arts &amp; Crafts</title>
    <link href="./resources/css/style.css" type="text/css" rel="stylesheet">
  </head>

  <body>
    <h1>Dasmoto's Arts &amp; Crafts</h1>

    

    <div class="item">
      <h2 id="brush">Brushes</h2>
      <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" alt="Hacksaw"/>
      <h3>Hacksaw Brushes</h3>
      <p>
        Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price">Starting at $3.00 / brush.</span>
      </p>
    </div>

    

    <div class="item">
      <h2 id="frame">Frames</h2>
      <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/frames.jpeg" alt="Frames"/>
      <h3>Art Frames (assorted)</h3>
      <p>
        Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. <span class="price">Starting at $2.00 / frame.</span>
      </p>
    </div>

    

    <div class="item">
      <h2 id="paint">Paint</h2>
      <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/finnish.jpeg" alt="Finnish Paint"/>
      <h3>Clean Finnish Paint</h3>
      <p>
        Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="price">Starting at $5.00 / tube.</span>
      </p>
    </div>

  </body>
</html>

**Comment by Mctavish38** [comment]
/* Universal styles */
h1,
h2,
h3,
p {
  font-family: "Helvetica", sans-serif;
}

/* H1 styles */

h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}

/* H2 styles */

.item h2 {
  font-size: 32px;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}

/* Span styles */

.price {
  font-weight: bold;
  color: blue;
}

**Comment by jim-rosales** [comment]
Hey, Berry, I downloaded the code you sent me, and it seems to be working fine. Did you save your project and reload the page? Also the colors you were referring to did you mean the header colors of the price blue color?

**Comment by Mctavish38** [comment]
Realy sorry for the delay in getting back to you. I am taking this course alongside a busy work schedule.
I had trouble with reloading my code on Atom hence the problems. Totally my mistake.

Thank you for all the help lets see if I can improve my code in the future!

**Comment by jim-rosales** [comment]
No worries glad I could help! You'll improve tremendously over time just keep practicing!
